=begin
#ocrapi

#The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveOcrApiClient::PdfToTextResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PdfToTextResponse' do
  before do
    # run before each test
    @instance = CloudmersiveOcrApiClient::PdfToTextResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PdfToTextResponse' do
    it 'should create an instance of PdfToTextResponse' do
      expect(@instance).to be_instance_of(CloudmersiveOcrApiClient::PdfToTextResponse)
    end
  end
  describe 'test attribute "successful"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "ocr_pages"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
