=begin
#ocrapi

#The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'cloudmersive-ocr-api-client/api_client'
require 'cloudmersive-ocr-api-client/api_error'
require 'cloudmersive-ocr-api-client/version'
require 'cloudmersive-ocr-api-client/configuration'

# Models
require 'cloudmersive-ocr-api-client/models/business_card_recognition_result'
require 'cloudmersive-ocr-api-client/models/field_result'
require 'cloudmersive-ocr-api-client/models/form_definition_template'
require 'cloudmersive-ocr-api-client/models/form_field_definition'
require 'cloudmersive-ocr-api-client/models/form_recognition_result'
require 'cloudmersive-ocr-api-client/models/form_table_column_definition'
require 'cloudmersive-ocr-api-client/models/form_table_definition'
require 'cloudmersive-ocr-api-client/models/get_page_angle_result'
require 'cloudmersive-ocr-api-client/models/image_to_lines_with_location_result'
require 'cloudmersive-ocr-api-client/models/image_to_text_response'
require 'cloudmersive-ocr-api-client/models/image_to_words_with_location_result'
require 'cloudmersive-ocr-api-client/models/ocr_line_element'
require 'cloudmersive-ocr-api-client/models/ocr_page_result'
require 'cloudmersive-ocr-api-client/models/ocr_page_result_with_lines_with_location'
require 'cloudmersive-ocr-api-client/models/ocr_page_result_with_words_with_location'
require 'cloudmersive-ocr-api-client/models/ocr_photo_text_element'
require 'cloudmersive-ocr-api-client/models/ocr_word_element'
require 'cloudmersive-ocr-api-client/models/pdf_to_lines_with_location_result'
require 'cloudmersive-ocr-api-client/models/pdf_to_text_response'
require 'cloudmersive-ocr-api-client/models/pdf_to_words_with_location_result'
require 'cloudmersive-ocr-api-client/models/photo_to_words_with_location_result'
require 'cloudmersive-ocr-api-client/models/point'
require 'cloudmersive-ocr-api-client/models/receipt_line_item'
require 'cloudmersive-ocr-api-client/models/receipt_recognition_result'
require 'cloudmersive-ocr-api-client/models/table_cell_result'
require 'cloudmersive-ocr-api-client/models/table_result'
require 'cloudmersive-ocr-api-client/models/table_row_result'

# APIs
require 'cloudmersive-ocr-api-client/api/image_ocr_api'
require 'cloudmersive-ocr-api-client/api/pdf_ocr_api'
require 'cloudmersive-ocr-api-client/api/preprocessing_api'
require 'cloudmersive-ocr-api-client/api/receipts_api'

module CloudmersiveOcrApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveOcrApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
